### ISSUE TITLE
Add social channels for communication

### ISSUE THREAD

**Issue by zvonimirr** [zvonimirr/tenantee#165]
- [ ] Telegram
- [ ] Viber
- [ ] WhatsApp
- [ ] Messenger

**Comment by bleakprestiger** [comment]
Can I Take This Issue ? @zvonimirr

**Comment by bleakprestiger** [comment]
Where We Would Have To Add The Communication Channels In The App ? In Which Section ?

**Comment by bleakprestiger** [comment]
Where We Would Have To Add The Communication Channels In The App ? In Which Section ? We Could Achieve This By Using FusionAuth.

**Comment by zvonimirr** [comment]
This is actually a backend issue. If you're comfortable with Elixir I suggest adding another table that contains the type of social channel, the data (number, handle etc.) and the tenant ID

**Comment by bleakprestiger** [comment]
Sure I would get these columns added in the table.

**Comment by zvonimirr** [comment]
Go on then 😄

**Comment by zvonimirr** [comment]
Yes. Be sure to follow the style of the previous entities.

**Comment by bleakprestiger** [comment]
sure

**Comment by bleakprestiger** [comment]
I had one doubt, the tenant ID column, that has to be added in the communication_channels, will be a foreign key referring to the tenant ID in the tenant schema ?

**Comment by bleakprestiger** [comment]
also, could you suggest name for the table ? currently i am planning to use `social_channels` for the table.

**Comment by zvonimirr** [comment]
> I had one doubt, the tenant ID column, that has to be added in the communication_channels, will be a foreign key referring to the tenant ID in the tenant schema ?

Yes



> also, could you suggest name for the table ? currently i am planning to use `social_channels` for the table.

I am leaning more towards communication_channels as e-mail isn't really a "social channel"
