### ISSUE TITLE
Align name with an icon in the tenant card (UI)

### ISSUE THREAD

**Issue by zvonimirr** [zvonimirr/tenantee#170]
For names that are longer icon and the text aren't aligned properly

![image](https://user-images.githubusercontent.com/18758022/204523066-5a5d7013-c719-4b45-9634-daeb31cfee47.png)

**Comment by zvonimirr** [comment]
Reported by @MilaFazekas

@allcontributors please add @MilaFazekas for bug reports

**Comment by MilaFazekas** [comment]
i will fix this

**Comment by zvonimirr** [comment]
Thanks :)
