### ISSUE TITLE
Allow manipulation of expenses from the UI

### ISSUE THREAD

**Issue by zvonimirr** [zvonimirr/tenantee#183]

**Comment by bleakprestiger** [comment]
Can I Take this issue ?

**Comment by zvonimirr** [comment]
Sure! You'll actually have to wait until #163 is complete but that should be very soon 😄

**Comment by zvonimirr** [comment]
#184 is merged 😃 you can working start on this

**Comment by bleakprestiger** [comment]
Okay Sure. Tomorrow I Will Start Working On This.

**Comment by zvonimirr** [comment]
This issue is outdated due to #391
