### ISSUE TITLE
Show net income/net expenses on the front page (UI)

### ISSUE THREAD

**Issue by zvonimirr** [zvonimirr/tenantee#198]

**Comment by bleakprestiger** [comment]
Can I Also Take This Issue ?

**Comment by zvonimirr** [comment]
Sure, but could finish the previous assignments first?
If no one takes this in the meantime you can have it

**Comment by BaluDeshamoni** [comment]
Is the issue still open. can I try this issue.

**Comment by zvonimirr** [comment]
Sure thing! It's still open

**Comment by BaluDeshamoni** [comment]
![error](https://user-images.githubusercontent.com/88838021/233772219-bea4132a-083c-4eae-a6ea-45cc00267cb6.PNG)


Having issue while running backend. Can I get some assistance as I am new to phoenix.

**Comment by zvonimirr** [comment]
@BaluDeshamoni 

https://elixirforum.com/t/mix-elixir-command-issue-init-terminating-in-do-boot/35494/5

**Comment by HarshithaSivalingala** [comment]
Hey, I have run the project using docker-compose, frontend is running but the backend on localhost:4000 is not reachable.

**Comment by zvonimirr** [comment]
Sure thing.

It seems we have a bit of an issue with BE at the moment (see #346).
I'll fix it ASAP

**Comment by zvonimirr** [comment]
@HarshithaSivalingala please keep in mind that Docker will run the API in production mode

**Comment by HarshithaSivalingala** [comment]
So, what's the other alternative to run the project, can you please guide me on what are the prerequisite commands to run before running 'mix' commands as mentioned in README file. @zvonimirr

**Comment by zvonimirr** [comment]
The alternative is to run it locally.
I use Docker just for the database.
There are no prerequisite commands. You need to have Elixir and Node installed on your machine.

**Comment by HarshithaSivalingala** [comment]
Thank you so much !! I'll look into it.

**Comment by zvonimirr** [comment]
This issue is outdated due to #391.
