### ISSUE TITLE
If communication is supported, make a link instead of text (UI)

### ISSUE THREAD

**Issue by zvonimirr** [zvonimirr/tenantee#275]
If the type is a valid key of TYPE_TO_ICON (TenantCommunicationList.tsx:27), we should render a link instead of text

**Comment by sawankarya2000** [comment]
Can i take this issue?

**Comment by zvonimirr** [comment]
Sure thing 😄

**Comment by sawankarya2000** [comment]
Sorry,Not Able to deal with the issue.

**Comment by zvonimirr** [comment]
Alright
