### ISSUE TITLE
Return monthly expenses for current month via API

### ISSUE THREAD

**Issue by zvonimirr** [zvonimirr/tenantee#344]
As same as we have the monthly revenue, it would be great to sum up all the expenses on the server instead of grouping them on the client side.

**Comment by Erik-McKelvey** [comment]
I don't have much experience working with elixir but I would like to help out with this if that's okay

**Comment by zvonimirr** [comment]
Sure @Erik-McKelvey. There is an example of how I summed up the monthly profits so you can go from there. You don't need to apply the tax to expenses though

**Comment by zvonimirr** [comment]
@Erik-McKelvey this issue is outdated due to #391, but I will start opening new issues so maybe you could pick some of them up?

**Comment by Erik-McKelvey** [comment]
@zvonimirr Hey that's alright sorry that I took so long I was learning Elixir and got busy in my last semester of school. I'll be happy to assign another task in a little while!

**Comment by zvonimirr** [comment]
No problem,  @Erik-McKelvey 
I'm setting up Credo & Sobelow for now but new issues should be ready today around 10pm

**Comment by zvonimirr** [comment]
@Erik-McKelvey the issues were created. Take a look and see if there's some you might like 😄
