### ISSUE TITLE
bug: Backend docker container fails to start

### ISSUE THREAD

**Issue by Erik-McKelvey** [zvonimirr/tenantee#346]
**Describe the bug**
When running `docker-compose up` the backend fails with the following error:
```
tenantee-backend-1   | exec ./run.sh: no such file or directory
tenantee-backend-1 exited with code 1
```
The other two containers run correctly.

**To Reproduce**
1. `docker-compose up`

**Expected behavior**
The backend container should execute `run.sh`

**Desktop:**
 - OS: Windows 10 Home 22H2

**Comment by zvonimirr** [comment]
Thanks!

It seems that the `run.sh` script is missing from the Docker image. We probably forgot to copy it in the Dockerfile
