### ISSUE TITLE
FEATURE: Generate rental agreements

### ISSUE THREAD

**Issue by zvonimirr** [zvonimirr/tenantee#421]
**Is your feature request related to a problem? Please describe.**
Generating rental agreements could prove useful for many landlords.

**Describe the solution you'd like**
Creating a template and saving it in a template seems like a good idea.

**Additional context**
Adding a configurable option is crucial because different people speak different languages.

**Comment by Ganesh1521** [comment]
Hi, I can help to solve this issue

Set up a Node.js environment:
Create a folder structure for your project and initialize a Node.js project:
bash
mkdir rental-agreement-generator
cd rental-agreement-generator
npm init -y
npm install express ejs
Create a basic Node.js server with Express:
Create a file named server.js in your project folder and add the following code:

const express = require('express');
const app = express();
const port = 3000;

app.set('view engine', 'ejs');
app.use(express.urlencoded({ extended: true }));

app.get('/', (req, res) => {
  res.render('index');
});

app.post('/generate-agreement', (req, res) => {
  // Here you would generate a new rental agreement based on the tenant's data
 
  res.send('Rental agreement generated successfully!');
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});

Create an index.ejs file in a folder named views:

<!DOCTYPE html>
<html>
<head>
    <title>Rental Agreement Generator</title>
</head>
<body>
    <h1>Rental Agreement Generator</h1>
    <form action="/generate-agreement" method="POST">
       
        <label for="tenant-name">Tenant Name:</label>
        <input type="text" id="tenant-name" name="tenant-name" required>

        <label for="property-address">Property Address:</label>
        <input type="text" id="property-address" name="property-address" required>

        <label for="rent-amount">Monthly Rent Amount:</label>
        <input type="number" id="rent-amount" name="rent-amount" required>

        <label for="lease-term">Lease Term (in months):</label>
        <input type="number" id="lease-term" name="lease-term" required>

        <label for="start-date">Lease Start Date:</label>
        <input type="date" id="start-date" name="start-date" required>

        <label for="end-date">Lease End Date:</label>
        <input type="date" id="end-date" name="end-date" required>

        <label for="security-deposit">Security Deposit:</label>
        <input type="number" id="security-deposit" name="security-deposit" required>

        <label for="additional-terms">Additional Terms:</label>
        <textarea id="additional-terms" name="additional-terms" rows="4"></textarea>

        <input type="checkbox" id="agree" name="agree" required>
        <label for="agree">I agree to the terms and conditions of the rental agreement.</label>

        <button type="submit">Submit</button>
    </form>
</body>
</html>





Create an index.ejs file in a folder named views:
Create a folder named views in your project directory, and inside it, create an index.ejs file. This file will contain the HTML form where tenants can request a new rental agreement:

html

Run the server:
Execute the following command in your project directory to start the Node.js server:



Access the website:
Open your web browser and go to http://localhost:3000 to access the rental agreement generator form. Users can fill out the form to request a new rental agreement.


This will automatically create rental agreement every month

**Comment by zvonimirr** [comment]
@Ganesh1521
This is all well and nice (even though it seems like an AI generated answer), but please keep in mind that this project doesn't use Node.

If you really wish to contribute fork the project, read the README and open a PR

**Comment by mrahmatu** [comment]
Hello, I am looking to contribute to an open source application as a part of my final project for a course. I have a team of five members, and I see four open issues currently. I wanted to know if this project is active, and if it would be viable for us to work on it.

**Comment by zvonimirr** [comment]
Hello @mrahmatu 😄

Yeah, the project is still open, however I didn't get much chance to develop it as I was busy with other things.
As far as the issues go, feel free to grab any of them and code away 👍🏻

**Comment by mrahmatu** [comment]
Okay, sounds good. So, if we do work on issues and complete them, what are the chances of getting our PRs accepted? We get a bonus if our changes are implemented :)

**Comment by zvonimirr** [comment]
If the work is completed properly 100% 😄 
Jokes aside, if you're looking for something somewhat easier you may look into #404

**Comment by mrahmatu** [comment]
I think even getting our changes reviewed would be good. Thank you!

**Comment by zvonimirr** [comment]
No problem 😃 
Good luck and have fun!
P.S. You can comment on #404 so that I can assign you

**Comment by mrahmatu** [comment]
I would like to work on this issue please.

**Comment by mrahmatu** [comment]
Hello, I am facing an issue with the setup. How can I contact you @zvonimirr ?

**Comment by mrahmatu** [comment]
Our plan is to make a button called "Generate agreement" on each property card that belongs to the landlord. Once the user clicks on it, it should take t he user to a form that they should fill for inputs required to generate the agreement. These inputs are then saved into the database and it is then used to draft the agreement. Once an agreement has been generated the button's text should change to "View Agreement". Clicking on the button, the user (landlord) should be able to view the agreement, or download it as a pdf.

**Comment by zvonimirr** [comment]
That seems reasonable 👍🏻
